apiVersion: apps/v1
kind: Deployment
metadata:
  name: beercatalogue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: beercatalogue
  template:
    metadata:
      labels:
        app: beercatalogue
    spec:
      containers:
        - name: beercatalogue
          image: beercatalogue:latest
          ports:
            - containerPort: 8080